
parameters:
  - name: applicationName
    type: string

stages:

- stage: build
  pool:
    vmImage: windows-latest
  jobs:
  - job: build
    steps:
    - powershell: |
        Write-Host "Building app ${{ parameters.applicationName }}"
      displayName: My build job

- stage: deploy
  dependsOn: build  
  pool:
    vmImage: windows-latest
  jobs:
    - deployment: 
      environment: dev
      strategy:
        runOnce:
          deploy:
            steps:
              - powershell: |
                  Write-Host "Deploying app ${{ parameters.applicationName }}"
                displayName: My deploy job
